require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.5

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/FileName:
  Exclude:
    - lib/notifications-rails.rb
    - notification-*/**/lib/notification-*.rb

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
