require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
    - '**/spec/support/rails_app/db/schema.rb'
  NewCops: enable
  TargetRubyVersion: 2.7

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Exclude:
    - '**/*_spec.rb'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Naming/FileName:
  Exclude:
    - lib/notifications-rails.rb
    - notification-*/**/lib/notification-*.rb

RSpec/ChangeByZero:
  Enabled: False

Rails/DynamicFindBy:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NoExpectationExample:
  AllowedPatterns:
    - ^expect_
    - ^assert_
    - ^test_
    - ^allow

RSpec/PendingWithoutReason:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/PerlBackrefs:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
