language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec rspec notification-handler
  - bundle exec rspec notification-pusher
  - bundle exec rspec notification-pusher/notification-pusher-actionmailer
  - bundle exec rspec notification-pusher/notification-pusher-onesignal
  - bundle exec rspec notification-renderer
  - bundle exec rspec notification-settings
