#!/bin/bash
bundle exec rspec
bundle exec rspec notification-handler
bundle exec rspec notification-pusher
bundle exec rspec notification-pusher/notification-pusher-actionmailer
bundle exec rspec notification-pusher/notification-pusher-onesignal
bundle exec rspec notification-renderer
bundle exec rspec notification-settings
