name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.5'

    steps:
      - uses: actions/checkout@v2
      - name: Remove Gemfile.lock
        run: rm Gemfile.lock
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # 'bundle install' and cache
      - name: Run Rubocop
        run: bundle exec rubocop
