name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
        - 'notification-handler/*'
        - 'notification-pusher/*'
        - 'notification-pusher/notification-pusher-actionmailer/*'
        - 'notification-pusher/notification-pusher-onesignal/*'
        - 'notification-renderer/*'
        - 'notification-settings/*'
        - '*'

    name: Publish ${{ matrix.package }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build ${{ matrix.package }}.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
