name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
        - 'notification-handler/*'
        - 'notification-pusher/*'
        - 'notification-pusher/notification-pusher-actionmailer/*'
        - 'notification-pusher/notification-pusher-onesignal/*'
        - 'notification-renderer/*'
        - 'notification-settings/*'
        - '*'

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1.1.1
      with:
        version: 2.6.x

    - name: Publish ${{ matrix.package }} to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build ${{ matrix.package }}.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} ${{ matrix.package }}.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.GPR_AUTH_TOKEN}}
        OWNER: jonhue

    - name: Publish ${{ matrix.package }} to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build ${{ matrix.package }}.gemspec
        gem push ${{ matrix.package }}.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
